-- ==========================================================
--  SKYARS ERP — Database Schema Setup for Supabase
--  Execute this script in your Supabase SQL Editor
-- ==========================================================

-- ----------------------------------------------------------
-- 1. Users Table
-- Extends Supabase auth.users to store roles & designations
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE,
    role TEXT CHECK (role IN ('admin', 'intern')) DEFAULT 'intern' NOT NULL,
    designation TEXT DEFAULT 'Intern' NOT NULL,
    status TEXT CHECK (status IN ('Active', 'Inactive')) DEFAULT 'Active' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------
-- 2. Tasks Table
-- Stores tasks assigned to interns
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tasks (
    id TEXT PRIMARY KEY, -- E.g. 'TSK-001'
    title TEXT NOT NULL,
    description TEXT,
    status TEXT CHECK (status IN ('To-Do', 'In Progress', 'Done')) DEFAULT 'To-Do' NOT NULL,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    due_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------
-- 3. Attendance Table
-- Records check-in logs for interns
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    date DATE DEFAULT CURRENT_DATE NOT NULL,
    check_in TIME WITH TIME ZONE DEFAULT CURRENT_TIME NOT NULL,
    status TEXT CHECK (status IN ('Present', 'Absent', 'Late')) DEFAULT 'Present' NOT NULL,
    UNIQUE (user_id, date)
);

-- Enable RLS
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;

-- ----------------------------------------------------------
-- 4. Daily Status Reports (DSRs) Table
-- Records status reports submitted by interns
-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dsrs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    task_id TEXT REFERENCES public.tasks(id) ON DELETE SET NULL,
    content TEXT NOT NULL,
    hours_spent NUMERIC(4, 2) DEFAULT 0.0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.dsrs ENABLE ROW LEVEL SECURITY;


-- ==========================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================================

-- --- Users Policies ---
CREATE POLICY "Allow public read on users" ON public.users
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow admin insert on users" ON public.users
    FOR INSERT TO authenticated WITH CHECK (
        (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
    );

CREATE POLICY "Allow admin update on users" ON public.users
    FOR UPDATE TO authenticated USING (
        (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
    );

CREATE POLICY "Allow admin delete on users" ON public.users
    FOR DELETE TO authenticated USING (
        (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
    );

-- --- Tasks Policies ---
CREATE POLICY "Allow users to view assigned tasks" ON public.tasks
    FOR SELECT TO authenticated USING (
        auth.uid() = user_id OR (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
    );

CREATE POLICY "Allow users to update their task status" ON public.tasks
    FOR UPDATE TO authenticated USING (
        auth.uid() = user_id OR (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
    ) WITH CHECK (
        auth.uid() = user_id OR (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
    );

CREATE POLICY "Allow admin all on tasks" ON public.tasks
    FOR ALL TO authenticated USING (
        (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
    );

-- --- Attendance Policies ---
CREATE POLICY "Allow users to view attendance" ON public.attendance
    FOR SELECT TO authenticated USING (
        auth.uid() = user_id OR (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
    );

CREATE POLICY "Allow users to check-in" ON public.attendance
    FOR INSERT TO authenticated WITH CHECK (
        auth.uid() = user_id
    );

CREATE POLICY "Allow admin all on attendance" ON public.attendance
    FOR ALL TO authenticated USING (
        (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
    );

-- --- DSR Policies ---
CREATE POLICY "Allow users to view DSRs" ON public.dsrs
    FOR SELECT TO authenticated USING (
        auth.uid() = user_id OR (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
    );

CREATE POLICY "Allow users to submit DSRs" ON public.dsrs
    FOR INSERT TO authenticated WITH CHECK (
        auth.uid() = user_id
    );

CREATE POLICY "Allow admin all on DSRs" ON public.dsrs
    FOR ALL TO authenticated USING (
        (SELECT role FROM public.users WHERE id = auth.uid()) = 'admin'
    );


-- ==========================================================
-- AUTOMATION TRIGGER (NEW USER REGISTRATION)
-- Automatically inserts new Supabase auth users into public.users
-- ==========================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (id, name, email, role, designation, status)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
        new.email,
        COALESCE(new.raw_user_meta_data->>'role', 'intern'),
        COALESCE(new.raw_user_meta_data->>'designation', 'Intern'),
        'Active'
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
